# Path
export PATH=$HOME/bin:/usr/local/bin:$PATH

# oh-my-zsh Path
export ZSH="$HOME/.oh-my-zsh"

# Windows Home Dir
export WIN_HOME="/mnt/c/Users/thuon"

# oh-my-zsh Themes
# ZSH_THEME="robbyrussell"

# Plugins
plugins=(
	git
	zsh-autosuggestions
	zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Aliases
alias zedit="nano $HOME/.zshrc"
alias zsource="source $HOME/.zshrc"
alias apt-update="sudo nala update"
alias apt-upgrade="sudo nala upgrade"
alias apt-install="sudo nala install "
alias code="$WIN_HOME/AppData/Local/Programs/Microsoft\ VS\ Code/bin/code"
alias code-insiders="$WIN_HOME/AppData/Local/Programs/Microsoft\ VS\ Code\ Insiders/bin/code-insiders"

# Starship Prompt
export STARSHIP_DIR="$HOME/.config/starship"
export STARSHIP_CONFIG="$STARSHIP_DIR/starship.toml"
eval "$(starship init zsh)"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
